#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    if bld.env.HAVE_CHECK != 1:
        print("warning: check was not found, unit tests are disabled.")
        return

    if bld.is_install:
        return

    USE = ['duplex', 'CHECK']
    
    # tests
    bld.program(features='test', source='join.c', target='join', use=USE)
    bld.program(features='test', source='peer.c', target='peer', use=USE)

    import os
    if os.environ.get('GODUPLEX') is not None:
        bld.program(features='test', source='goduplex.c', target='goduplex', use=USE)
    else:
        print("warning: GODUPLEX is not defined, go duplex tests not running.")
    
    # show the summary
    from waflib.Tools import waf_unit_test
    bld.add_post_fun(waf_unit_test.summary)
    bld.add_post_fun(waf_unit_test.set_exit_code)
