#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    if bld.env.HAVE_CHECK != 1:
        print("warning: check was not found, unit tests are disabled.")
        return

    if bld.is_install:
        return
    
    # tests
    bld.program(features='test', source='join.c', target='join', use=['duplex', 'CHECK'])
    bld.program(features='test', source='peer.c', target='join', use=['duplex', 'CHECK'])
    
    # show the summary
    from waflib.Tools import waf_unit_test
    bld.add_post_fun(waf_unit_test.summary)
    bld.add_post_fun(waf_unit_test.set_exit_code)
